[project]
name = "hydromt_fiat"
description = "HydroMT plugin for Hydrological model for flood impact assessment and adaptation planning"
authors = [
  "Dirk Eilander<dirk.eilander@deltares.nl>",
  "Frederique de Groen<frederique.degroen@deltares.nl>",
  "Mario Fuentes Monjaraz<mario.fuentesmonjaraz@deltares.nl>",
  "Luis Rodriguez Galvez<luis.rodriguez@deltares.nl>",
  "Lieke Meijer<lieke.meijer@deltares.nl>",
  "Sarah Rautenbach<sarah.rautenbach@deltares.nl>",
  "Sam Vente<sam.vente@deltares.nl>",
]
channels = ["conda-forge"]
platforms = ["win-64"]

[feature.docs.tasks]
doctest = { cmd = [
	"sphinx-build",
	"-M",
	"doctest",
	"docs",
	"docs/_build",
	"-W",
] }
docs-build = { cmd = [
	"sphinx-build",
	"-M",
	"html",
	"docs",
	"docs/_build",
	"-W",
], depends-on = [
	"doctest",
] }
docs = { depends-on = ["docs-build"] } # alias
doc = { depends-on = ["docs-build"] } # alias
serve = { cmd = ["python", "-m", "http.server", "-d", "docs/_build/html"] }

[feature.dev.tasks]
lint = { cmd = ["pre-commit", "run", "--all"] }
fetch-test-db = { cmd = ["python", "tests/fetch_data.py"], outputs = [
	"tests/data/test_db",
] }
test = { cmd = ["pytest"], depends-on = ["fetch-test-db"]}
test-lf = { cmd = ["pytest", "--lf", "--tb=short"], depends-on = ["fetch-test-db"] }
test-err-warn = { cmd = ["pytest", "--tb=short", "-W", "error"], depends-on = ["fetch-test-db"] }
test-cov = { cmd = [
	"pytest",
	"--verbose",
	"--cov=hydromt",
	"--cov-report",
	"xml",
], depends-on = ["fetch-test-db"] }


[feature.py39.dependencies]
python = "3.9.*"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[environments]
default = {features = ["dev", "docs", "py310"], solve-group = "py310"}
dev = {features = ["dev", "py310"], solve-group = "py310"}
docs = {features = ["docs", "py310"], solve-group = "py310"}

full39 =  {features = ["dev", "docs", "py39"], solve-group = "py39"}
full310 = {features = ["dev", "docs", "py310"], solve-group = "py310"}
full311 = {features = ["dev", "docs", "py311"], solve-group = "py311"}
full312 = {features = ["dev", "docs", "py312"], solve-group = "py312"}
full313 = {features = ["dev", "docs", "py313"], solve-group = "py313"}


[dependencies]
census = "*"
gdal = ">=3.1"
geopandas = "*"
geopy = "*"
hydromt = "<1.0.0"
hydromt_sfincs = "*"
ipykernel = "*"
numpy = "*"
openpyxl = "*"
osmnx = "*"
pandas = "*"
pydantic = "*"
pyogrio = "*"
rasterio = "*"
requests = "*"
rioxarray = "*"
tomli = "*"
tomli-w = "*"
universal_pathlib = "*"

xarray = "*"
xarray-spatial = "*"
pint = "*"

[pypi-dependencies]
pycountry-convert = "*"
us = "*"

[feature.dev.dependencies]
pytest = "*"
ruff = "==0.6.8"
pre-commit = "*"
tqdm = "*"
python-dotenv = "*"
minio = "*"

[feature.docs.dependencies]
jupyterlab = "*"
matplotlib-base = "*"
mercantile = "*"
notebook = "*"
packaging = "*"
pydata-sphinx-theme = "*"
sphinx = "*"
nbsphinx = "*"

[feature.docs.pypi-dependencies]
sphinx_design = "*"
sphinx_autosummary_accessors = "*"
