## Global stuff
[project]
name = "hydromt_fiat"
version = "0.1.0"
description = "Pixi for HydroMT-FIAT."
authors = ["T.J. de Jong <tjalling.dejong@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]


## The different tasks of this project
[tasks]
# Installation
install = { depends_on = ["install-hydromt-fiat", "install-pre-commit"] }
install-hydromt-fiat = "pip install --no-deps --editable ."
install-pre-commit = "pre-commit install"

# Repo related tasks
lint = { cmd = ["pre-commit", "run", "--all"] }

# Docker related stuff (expand in future)
docker-clean = { cmd = ["docker", "system", "prune", "-f"] }

# Documentation generation
docs = { depends_on = ["html"] }
html = { cmd = ["sphinx-build", "-M", "html", "docs", "docs/_build", "-W"] }
serve = { cmd = ["python", "-m", "http.server", "8000", "-d", "docs/_build/html"] }

# Testing
test = { cmd = ["pytest"] }
test-lf = { cmd = ["pytest", "--lf", "--tb=short"] }
test-cov = { cmd = ["pytest", "--verbose", "--cov=hydromt_fiat", "--cov-report", "xml"] }
test-cov-local = { cmd = ["pytest", "--verbose", "--cov", "--cov-report", "html",] }

# Clean up (some of) the temporary files
clean = { depends_on = [
  "clean-env-files",
  "clean-bin",
  "clean-dist",
  "clean-docs",
  "clean-docs-example",
  "clean-docs-gen",
] }
clean-env-files = { cmd = ["rm", "-f", "*environment.yml"] }
clean-bin = { cmd = ["rm", "-rf", "bin"] }
clean-dist = {cmd = ["rm", "-rf", "dist"] }
clean-docs = { cmd = ["rm", "-rf", "docs/_build/html"] }
clean-docs-example = { cmd = ["rm", "-rf", "docs/_examples"] }
clean-docs-gen = { cmd = ["rm", "-rf", "docs/_generated"] }


## Dependencies
[dependencies]
dask = "*"
geopandas = "*"
hydromt = ">=1.0.0a"
numpy = "*"
requests = "*"
tomli = "*"
tomli-w = "*"
xarray = "*"
pip = ">=24.0,<25"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.all.dependencies]
setuptools = ">=61.0.0"

[feature.dev.dependencies]
pre-commit = "*"
ruff = "*"
pip = ">=23.1.2"

[feature.docs.dependencies]
nbsphinx = "*"
pydata-sphinx-theme = "*"
sphinx = "*"

[feature.docs.pypi-dependencies]
sphinx_autosummary_accessors = "*"
sphinx_design = "*"

[feature.examples.dependencies]
cartopy = "*"
jupyterlab = "*"
nbconvert = "7.13.1"
notebook = "*"

[feature.test.dependencies]
pytest = ">=2.7.3"
pytest-cov = "*"
pytest-mock = "*"
responses = "*"


## Define the environments
[environments]
default = { features = ["py312"], solve-group = "py312"}
dev = { features = ["py312", "all", "dev", "docs", "examples", "test"], solve-group = "py312" }
docs = { features = ["py312", "all", "docs", "examples"], solve-group = "py312"}
min = { features = ["py312"], solve-group = "py312"}
test-py312 = {features = ["py312", "all", "dev", "test"], solve-group = "py312"}
test-py311 = {features = ["py311", "all", "dev", "test"], solve-group = "py311"}
test-py310 = {features = ["py310", "all", "dev", "test"], solve-group = "py310"}
