---
name: Bug Report
description: Report incorrect behavior
labels: [bug, needs refinement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: hydomt_fiat version checks
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have checked that this bug exists on the latest version of hydomt_fiat.
          required: true
  - type: textarea
    id: example
    attributes:
      description: >
        Please provide a minimal, copy-pastable example or a link to a public repository that reproduces the behavior. If providing a copy pastable example,
        you may assume your in a clean up to date version of hydomt_fiat with a python enviroment active. In the case of a repository, ensure the repository
        has a README.md which includes intructions to reproduce the behaviour.
      label: Reproducible Example
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      description: >
        Please provide a description of the incorrect behaviour shown in the reproducible example
      label: Current behaviour
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      description: >
        Please provide a description of what you think the behaviour should be
      label: Desired behaviour
    validations:
      required: true
  - type: textarea
    id: task-list
    attributes:
      description: >
        Please provide a list of tasks that need to be completed before this issue can be closed.
      label: Task list
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      description: >
        Please add any other context about the bug here
      label: Additional context
    validations:
      required: false
