name: Feature Request
description: Propose an improvement for HydroMT-FIAT
# title: "Improvement: "
labels: [enhancement]

body:
  - type: dropdown
    id: checks
    attributes:
      description: What kind of feature request is this?
      label: Feature type
      options:
        - Adding new functionality
        - Changing existing functionality
        - Removing existing functionality
  - type: textarea
    id: description
    attributes:
      label: Improvement Description
      description: >
        Please provide a clear and concise description of what your proposed improvement is:
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Implementation Description
      description: >
        Please describe how this would be implemented:
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please add any other context about the improvement here:
