---
name: Create Test Cache
on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:
permissions:
  actions: write
  contents: write

jobs:
  cache:
    defaults:
      run:
        shell: bash -e -l {0}
    name: cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install aws CLI
        run: |
          pip install awscli

      - name: Download
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          aws --endpoint-url https://s3.deltares.nl \
            s3 cp s3://hydromt-fiat/global-data/v1.0.0/global-data.tar.gz \
            .cache/global-data.tar.gz
          aws --endpoint-url https://s3.deltares.nl \
            s3 cp s3://hydromt-fiat/test-data/v1.0.0/ ./.cache \
            --recursive

      - name: Untar
        run: |
          for file in .cache/*.tar.gz; do
            dirname=$(basename "$file" .tar.gz)
            target_dir=".cache/$dirname"
            mkdir -p "$target_dir"
            tar -xzf "$file" -C "$target_dir"
          done

      - name: Validate cache
        run: |
          if [ ! "$(ls -A .cache)" ]; then
            echo "Cache directory is empty. Exiting."
            exit 1
          fi

      - name: Upload cache
        uses: actions/cache/save@v5
        with:
          path: .cache
          key: test-data
          enableCrossOsArchive: true
