---
name: Test
on:
  workflow_call:
    inputs:
      os:               { type: string, required: true }
      python-version:   { type: string, required: true }

jobs:
  unit:
    defaults:
      run:
        shell: bash -e -l {0}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293
        with:
          pixi-version: "v0.54.1"
          environments: test-py${{ inputs.python-version }}
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Test
        run: |
          pixi run -e test-py${{ inputs.python-version }} test-cov

  integration:
    defaults:
      run:
        shell: bash -e -l {0}
    runs-on: ${{ inputs.os }}
    needs: unit
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293
        with:
          pixi-version: "v0.54.1"
          environments: test-py${{ inputs.python-version }}
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Test
        run: |
          pixi run -e test-py${{ inputs.python-version }} test-integration
